/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.qltv.ui;

import com.qltv.dao.NhanVienDAO;
import com.qltv.dao.TaiKhoanDAO;
import com.qltv.entity.NhanVien;
import com.qltv.entity.TaiKhoan;
import com.qltv.utils.MsgBox;
import com.qltv.utils.XDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class QLNhanVien extends javax.swing.JPanel {

    NhanVienDAO nvdao = new NhanVienDAO();
    TaiKhoanDAO tkdao = new TaiKhoanDAO();
    /**
     * Creates new form QLNhanVien
     */
    public QLNhanVien() {
        initComponents();
        fillTableNV();
        fillTableTaiKhoan();
    }

    public void fillTableNV(){
        DefaultTableModel model = (DefaultTableModel) tblNhanVien.getModel();
        model.setRowCount(0);
        try{
            List<NhanVien> list = nvdao.selectAll();
            for (NhanVien dg : list) {
                Object[] row = {
                    dg.getMa(),
                    dg.getTen(),
                    dg.getNam(),
                    dg.isGiotinh() ? "Nữ" : "Nam",
                    dg.getDiachi(),
                    dg.getSdt()
                };
                model.addRow(row);
                
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu sách!");
            e.printStackTrace();
        }
        
    }
    
    public void fillTableTaiKhoan() {
        DefaultTableModel modelSP = (DefaultTableModel) tblTaiKhoan.getModel();
        modelSP.setRowCount(0);
        jTabbedPane1.setSelectedIndex(1);
        List<TaiKhoan> listSP = new ArrayList<>();
        listSP = tkdao.SelectAll();
        try {
            for (TaiKhoan tv : listSP) {
                Object[] rows = new Object[]{
                    tv.getMatk(),
                    tv.getUser(),
                    tv.getPass(),
                    tv.isQuyen() ? "Quản lý" : "Nhân viên",
                    tv.getManv()
                };
                modelSP.addRow(rows);
            }
            
        } catch (Exception e) {
        }

    }
    
    private void clickTable() {
        int i = tblNhanVien.getSelectedRow();
        if (i > -1) {
            try {
                txtMa.setText(tblNhanVien.getValueAt(i, 0) + "");
                txtHoTen.setText(tblNhanVien.getValueAt(i, 1) + "");
                txtNamSinh.setText(tblNhanVien.getValueAt(i, 2) + "");
                if (String.valueOf(tblNhanVien.getValueAt(i, 3)) == "Nam") {
                    rdoNam.setSelected(true);
                } else if (String.valueOf(tblNhanVien.getValueAt(i, 3)).equals("Nữ")) {
                    rdoNu.setSelected(true);
                }
                txtDiaChi.setText(tblNhanVien.getValueAt(i, 4) + "");
                txtSDT.setText(tblNhanVien.getValueAt(i, 5) + "");
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn vào bảng");
        }

    }
    
    private void clickTableTK() {
        int i = tblTaiKhoan.getSelectedRow();
        if (i > -1) {
            try {
                txtMaTK.setText(tblTaiKhoan.getValueAt(i, 0) + "");
                txtUser.setText(tblTaiKhoan.getValueAt(i, 1) + "");
                txtMatKhau.setText(tblTaiKhoan.getValueAt(i, 2) + "");
                if (String.valueOf(tblTaiKhoan.getValueAt(i, 3)) == "Quản lý") {
                    rdoQuanLy.setSelected(true);
                } else if (String.valueOf(tblTaiKhoan.getValueAt(i, 3)).equals("Nhân viên")) {
                    rdoNhanVien.setSelected(true);
                }
                txtMa.setText(tblTaiKhoan.getValueAt(i, 4) + "");
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn vào bảng");
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        panelBorder1 = new com.qltv.swing.PanelBorder();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtMa = new com.qltv.swing.TextField();
        txtHoTen = new com.qltv.swing.TextField();
        txtNamSinh = new com.qltv.swing.TextField();
        txtDiaChi = new com.qltv.swing.TextField();
        jLabel1 = new javax.swing.JLabel();
        rdoNu = new javax.swing.JRadioButton();
        rdoNam = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        textField5 = new com.qltv.swing.TextField();
        button4 = new com.qltv.swing.Button();
        button1 = new com.qltv.swing.Button();
        button3 = new com.qltv.swing.Button();
        button2 = new com.qltv.swing.Button();
        jLabel2 = new javax.swing.JLabel();
        txtSDT = new com.qltv.swing.TextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaTK = new com.qltv.swing.TextField();
        txtUser = new com.qltv.swing.TextField();
        txtMatKhau = new com.qltv.swing.TextField();
        jLabel5 = new javax.swing.JLabel();
        rdoQuanLy = new javax.swing.JRadioButton();
        rdoNhanVien = new javax.swing.JRadioButton();
        button5 = new com.qltv.swing.Button();
        button6 = new com.qltv.swing.Button();
        button7 = new com.qltv.swing.Button();
        button8 = new com.qltv.swing.Button();
        jLabel6 = new javax.swing.JLabel();
        textField10 = new com.qltv.swing.TextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTaiKhoan = new javax.swing.JTable();

        panelBorder1.setPreferredSize(new java.awt.Dimension(1100, 630));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(153, 102, 0));
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(300, 80));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMa.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtMa.setLabelText("Mã nhân viên");
        txtMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaActionPerformed(evt);
            }
        });
        jPanel1.add(txtMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 273, -1));

        txtHoTen.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtHoTen.setLabelText("Họ & tên");
        jPanel1.add(txtHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 273, -1));

        txtNamSinh.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtNamSinh.setLabelText("Năm sinh");
        jPanel1.add(txtNamSinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 273, -1));

        txtDiaChi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtDiaChi.setLabelText("Địa chỉ");
        txtDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChiActionPerformed(evt);
            }
        });
        jPanel1.add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 273, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Giới tính");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, -1, -1));

        buttonGroup2.add(rdoNu);
        rdoNu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rdoNu.setForeground(new java.awt.Color(153, 153, 153));
        rdoNu.setText("Nữ");
        jPanel1.add(rdoNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, -1, -1));

        buttonGroup2.add(rdoNam);
        rdoNam.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rdoNam.setForeground(new java.awt.Color(153, 153, 153));
        rdoNam.setText("Nam");
        jPanel1.add(rdoNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, -1, -1));

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Năm sinh", "Giới tính", "Địa chỉ", "Số điện thoại"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanVien);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 570, 370));

        textField5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        textField5.setLabelText("Tìm kiếm");
        jPanel1.add(textField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 290, -1));

        button4.setText("Thêm");
        button4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        button4.setPreferredSize(new java.awt.Dimension(90, 50));
        jPanel1.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, -1, -1));

        button1.setText("Cập nhật");
        button1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        button1.setPreferredSize(new java.awt.Dimension(90, 50));
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, -1, -1));

        button3.setText("Xóa");
        button3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        button3.setPreferredSize(new java.awt.Dimension(90, 50));
        jPanel1.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, -1, -1));

        button2.setText("Mới");
        button2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        button2.setPreferredSize(new java.awt.Dimension(90, 50));
        jPanel1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 540, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 102, 0));
        jLabel2.setText("NHÂN VIÊN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        txtSDT.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtSDT.setLabelText("Số điện thoại");
        jPanel1.add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 270, -1));

        jTabbedPane1.addTab("NHÂN VIÊN", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 0));
        jLabel3.setText("Tên nhân viên: ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 0));
        jLabel4.setText("Chức vụ:  Quản lý");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        txtMaTK.setLabelText("Mã tài khoản");
        jPanel2.add(txtMaTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 193, 268, -1));

        txtUser.setLabelText("Tài khoản");
        jPanel2.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 257, 268, -1));

        txtMatKhau.setLabelText("Mật khẩu");
        jPanel2.add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 321, 268, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Chức vụ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 391, -1, -1));

        buttonGroup1.add(rdoQuanLy);
        rdoQuanLy.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rdoQuanLy.setForeground(new java.awt.Color(153, 153, 153));
        rdoQuanLy.setText("Quản lý");
        jPanel2.add(rdoQuanLy, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 413, -1, -1));

        buttonGroup1.add(rdoNhanVien);
        rdoNhanVien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rdoNhanVien.setForeground(new java.awt.Color(153, 153, 153));
        rdoNhanVien.setText("Nhân viên");
        jPanel2.add(rdoNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 413, -1, -1));

        button5.setText("Mới");
        button5.setPreferredSize(new java.awt.Dimension(75, 45));
        jPanel2.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, -1, -1));

        button6.setText("Cập nhật");
        button6.setPreferredSize(new java.awt.Dimension(75, 45));
        jPanel2.add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, -1, -1));

        button7.setText("Thêm");
        button7.setPreferredSize(new java.awt.Dimension(75, 45));
        jPanel2.add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, -1, -1));

        button8.setText("Xóa");
        button8.setPreferredSize(new java.awt.Dimension(75, 45));
        jPanel2.add(button8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 102, 0));
        jLabel6.setText("TÀI KHOẢN");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 200, -1));

        textField10.setLabelText("Tìm kiếm");
        jPanel2.add(textField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 290, -1));

        tblTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã tài khoản", "Username", "Password", "Quyền", "Mã nhân viên"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTaiKhoanMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblTaiKhoan);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 580, 370));

        jTabbedPane1.addTab("TÀI KHOẢN", jPanel2);

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChiActionPerformed

    private void txtMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaActionPerformed

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
            clickTable();
        }
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void tblTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTaiKhoanMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
            clickTableTK();
        }
    }//GEN-LAST:event_tblTaiKhoanMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.qltv.swing.Button button1;
    private com.qltv.swing.Button button2;
    private com.qltv.swing.Button button3;
    private com.qltv.swing.Button button4;
    private com.qltv.swing.Button button5;
    private com.qltv.swing.Button button6;
    private com.qltv.swing.Button button7;
    private com.qltv.swing.Button button8;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.qltv.swing.PanelBorder panelBorder1;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNhanVien;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JRadioButton rdoQuanLy;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTable tblTaiKhoan;
    private com.qltv.swing.TextField textField10;
    private com.qltv.swing.TextField textField5;
    private com.qltv.swing.TextField txtDiaChi;
    private com.qltv.swing.TextField txtHoTen;
    private com.qltv.swing.TextField txtMa;
    private com.qltv.swing.TextField txtMaTK;
    private com.qltv.swing.TextField txtMatKhau;
    private com.qltv.swing.TextField txtNamSinh;
    private com.qltv.swing.TextField txtSDT;
    private com.qltv.swing.TextField txtUser;
    // End of variables declaration//GEN-END:variables
}
