/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.qltv.ui;

/**
 *
 * @author Admin
 */
public class QLNhanVien extends javax.swing.JPanel {

    /**
     * Creates new form QLNhanVien
     */
    public QLNhanVien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new com.qltv.swing.PanelBorder();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        textField1 = new com.qltv.swing.TextField();
        textField2 = new com.qltv.swing.TextField();
        textField3 = new com.qltv.swing.TextField();
        textField4 = new com.qltv.swing.TextField();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        textField5 = new com.qltv.swing.TextField();
        button4 = new com.qltv.swing.Button();
        button1 = new com.qltv.swing.Button();
        button3 = new com.qltv.swing.Button();
        button2 = new com.qltv.swing.Button();
        jLabel2 = new javax.swing.JLabel();
        textField6 = new com.qltv.swing.TextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textField7 = new com.qltv.swing.TextField();
        textField8 = new com.qltv.swing.TextField();
        textField9 = new com.qltv.swing.TextField();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        button5 = new com.qltv.swing.Button();
        button6 = new com.qltv.swing.Button();
        button7 = new com.qltv.swing.Button();
        button8 = new com.qltv.swing.Button();
        jLabel6 = new javax.swing.JLabel();
        textField10 = new com.qltv.swing.TextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        panelBorder1.setPreferredSize(new java.awt.Dimension(1100, 630));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(153, 102, 0));
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(300, 80));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textField1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        textField1.setLabelText("Mã nhân viên");
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });
        jPanel1.add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 273, -1));

        textField2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        textField2.setLabelText("Họ & tên");
        jPanel1.add(textField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 273, -1));

        textField3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        textField3.setLabelText("Năm sinh");
        jPanel1.add(textField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 273, -1));

        textField4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        textField4.setLabelText("Địa chỉ");
        textField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField4ActionPerformed(evt);
            }
        });
        jPanel1.add(textField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 273, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Giới tính");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, -1, -1));

        jRadioButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(153, 153, 153));
        jRadioButton1.setText("Nữ");
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, -1, -1));

        jRadioButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(153, 153, 153));
        jRadioButton2.setText("Nam");
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 570, 370));

        textField5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        textField5.setLabelText("Tìm kiếm");
        jPanel1.add(textField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 290, -1));

        button4.setText("Thêm");
        button4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        button4.setPreferredSize(new java.awt.Dimension(90, 50));
        jPanel1.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, -1, -1));

        button1.setText("Cập nhật");
        button1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        button1.setPreferredSize(new java.awt.Dimension(90, 50));
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, -1, -1));

        button3.setText("Xóa");
        button3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        button3.setPreferredSize(new java.awt.Dimension(90, 50));
        jPanel1.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, -1, -1));

        button2.setText("Mới");
        button2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        button2.setPreferredSize(new java.awt.Dimension(90, 50));
        jPanel1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 540, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 102, 0));
        jLabel2.setText("NHÂN VIÊN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        textField6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        textField6.setLabelText("Số điện thoại");
        jPanel1.add(textField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 270, -1));

        jTabbedPane1.addTab("NHÂN VIÊN", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 0));
        jLabel3.setText("Tên nhân viên: ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 0));
        jLabel4.setText("Chức vụ:  Quản lý");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        textField7.setLabelText("Mã tài khoản");
        jPanel2.add(textField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 193, 268, -1));

        textField8.setLabelText("Tài khoản");
        jPanel2.add(textField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 257, 268, -1));

        textField9.setLabelText("Mật khẩu");
        jPanel2.add(textField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 321, 268, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Chức vụ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 391, -1, -1));

        jRadioButton3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(153, 153, 153));
        jRadioButton3.setText("Quản lý");
        jPanel2.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 413, -1, -1));

        jRadioButton4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(153, 153, 153));
        jRadioButton4.setText("Nhân viên");
        jPanel2.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 413, -1, -1));

        button5.setText("Mới");
        button5.setPreferredSize(new java.awt.Dimension(75, 45));
        jPanel2.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, -1, -1));

        button6.setText("Cập nhật");
        button6.setPreferredSize(new java.awt.Dimension(75, 45));
        jPanel2.add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, -1, -1));

        button7.setText("Thêm");
        button7.setPreferredSize(new java.awt.Dimension(75, 45));
        jPanel2.add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, -1, -1));

        button8.setText("Xóa");
        button8.setPreferredSize(new java.awt.Dimension(75, 45));
        jPanel2.add(button8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 102, 0));
        jLabel6.setText("TÀI KHOẢN");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 200, -1));

        textField10.setLabelText("Tìm kiếm");
        jPanel2.add(textField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 290, -1));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 580, 370));

        jTabbedPane1.addTab("TÀI KHOẢN", jPanel2);

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField4ActionPerformed

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.qltv.swing.Button button1;
    private com.qltv.swing.Button button2;
    private com.qltv.swing.Button button3;
    private com.qltv.swing.Button button4;
    private com.qltv.swing.Button button5;
    private com.qltv.swing.Button button6;
    private com.qltv.swing.Button button7;
    private com.qltv.swing.Button button8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private com.qltv.swing.PanelBorder panelBorder1;
    private com.qltv.swing.TextField textField1;
    private com.qltv.swing.TextField textField10;
    private com.qltv.swing.TextField textField2;
    private com.qltv.swing.TextField textField3;
    private com.qltv.swing.TextField textField4;
    private com.qltv.swing.TextField textField5;
    private com.qltv.swing.TextField textField6;
    private com.qltv.swing.TextField textField7;
    private com.qltv.swing.TextField textField8;
    private com.qltv.swing.TextField textField9;
    // End of variables declaration//GEN-END:variables
}
