/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qltv.ui;

/**
 *
 * @author RAVEN
 */
public class QLSach extends javax.swing.JPanel {

    /**
     * Creates new form Form_1
     */
    public QLSach() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        button5 = new com.qltv.swing.Button();
        txt = new com.qltv.swing.TextField();
        textField3 = new com.qltv.swing.TextField();
        textField4 = new com.qltv.swing.TextField();
        button6 = new com.qltv.swing.Button();
        button7 = new com.qltv.swing.Button();
        button8 = new com.qltv.swing.Button();
        button9 = new com.qltv.swing.Button();
        jLabel1 = new javax.swing.JLabel();
        combobox1 = new com.qltv.swing.Combobox();
        combobox2 = new com.qltv.swing.Combobox();
        combobox3 = new com.qltv.swing.Combobox();
        combobox4 = new com.qltv.swing.Combobox();
        jPanel2 = new javax.swing.JPanel();
        textField1 = new com.qltv.swing.TextField();
        button1 = new com.qltv.swing.Button();
        button2 = new com.qltv.swing.Button();
        button3 = new com.qltv.swing.Button();
        button4 = new com.qltv.swing.Button();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(153, 102, 0));
        jTabbedPane1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 608));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ảnh", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Times New Roman", 0, 18), new java.awt.Color(153, 102, 0))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 440, 440));

        button5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qltv/icon/camera.png"))); // NOI18N
        button5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        button5.setPreferredSize(new java.awt.Dimension(90, 50));
        jPanel1.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, -1, -1));

        txt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt.setLabelText("Tên sách");
        txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActionPerformed(evt);
            }
        });
        jPanel1.add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 570, -1));

        textField3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        textField3.setLabelText("Năm sản xuất");
        jPanel1.add(textField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 230, 270, 40));

        textField4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        textField4.setLabelText("Số lượng");
        jPanel1.add(textField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 270, 40));

        button6.setText("Cập nhật");
        button6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        button6.setPreferredSize(new java.awt.Dimension(90, 50));
        jPanel1.add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, -1, -1));

        button7.setText("Xóa");
        button7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        button7.setPreferredSize(new java.awt.Dimension(90, 50));
        jPanel1.add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 420, -1, -1));

        button8.setText("Mới");
        button8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        button8.setPreferredSize(new java.awt.Dimension(90, 50));
        jPanel1.add(button8, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 420, -1, -1));

        button9.setText("Thêm");
        button9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        button9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        button9.setPreferredSize(new java.awt.Dimension(90, 50));
        button9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(button9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 102, 0));
        jLabel1.setText("SÁCH");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));

        combobox1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        combobox1.setLabeText("Loại sách");
        jPanel1.add(combobox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 270, -1));

        combobox2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        combobox2.setLabeText("Nhà xuất bản");
        jPanel1.add(combobox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 270, 40));

        combobox3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        combobox3.setLabeText("Kệ sách");
        jPanel1.add(combobox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 310, 270, 40));

        combobox4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        combobox4.setLabeText("Tác giả");
        jPanel1.add(combobox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 270, -1));

        jTabbedPane1.addTab("THÔNG TIN", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textField1.setForeground(new java.awt.Color(153, 102, 0));
        textField1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        textField1.setLabelText("Tìm kiếm");
        jPanel2.add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 21, 415, -1));

        button1.setText("|<");
        button1.setPreferredSize(new java.awt.Dimension(60, 41));
        jPanel2.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 100, -1, -1));

        button2.setText(">|");
        button2.setPreferredSize(new java.awt.Dimension(60, 41));
        jPanel2.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 100, -1, -1));

        button3.setText(">>");
        button3.setPreferredSize(new java.awt.Dimension(60, 41));
        jPanel2.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 100, -1, -1));

        button4.setText("<<");
        button4.setPreferredSize(new java.awt.Dimension(60, 41));
        jPanel2.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 100, -1, -1));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Times New Roman", 0, 14), new java.awt.Color(153, 102, 0))); // NOI18N
        jScrollPane2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setGridColor(new java.awt.Color(255, 255, 255));
        jTable2.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 1020, 400));

        jTabbedPane1.addTab("DANH SÁCH", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.qltv.swing.Button button1;
    private com.qltv.swing.Button button2;
    private com.qltv.swing.Button button3;
    private com.qltv.swing.Button button4;
    private com.qltv.swing.Button button5;
    private com.qltv.swing.Button button6;
    private com.qltv.swing.Button button7;
    private com.qltv.swing.Button button8;
    private com.qltv.swing.Button button9;
    private com.qltv.swing.Combobox combobox1;
    private com.qltv.swing.Combobox combobox2;
    private com.qltv.swing.Combobox combobox3;
    private com.qltv.swing.Combobox combobox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private com.qltv.swing.TextField textField1;
    private com.qltv.swing.TextField textField3;
    private com.qltv.swing.TextField textField4;
    private com.qltv.swing.TextField txt;
    // End of variables declaration//GEN-END:variables
}
